### PR TITLE
Add mboukhalfa affiliation

### PR DESCRIPTION
**Pull request by mboukhalfa**
Signed-off-by: Mohammed Boukhalfa Mohammed.boukhalfa@est.tech

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Why closed? I was just about to merge - please reopen if you want.

**Comment by mboukhalfa** [comment]
> Why closed? I was just about to merge - please reopen if you want.

It is showing check failed, I am not sure what is the issue was planning to check later

**Comment by lukaszgryglicki** [comment]
Ohh DCO, you can ignore this, I'll merge your PR.

**Comment by mboukhalfa** [comment]
> Ohh DCO, you can ignore this, I'll merge your PR.

Thanks :)

**Pull request merged**
