### PR TITLE
lentzi90: update country

### PR DESCRIPTION
**Pull request by lentzi90**
Signed-off-by: Lennart Jern <lennart.jern@est.tech>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
I can't see changes... can you just post diff here instead? like or just let me know user login and country value to update?

**Comment by lentzi90** [comment]
Sure thing!
```
❯ diff github_users_master.json github_users_patched.json 
42861,42862c42861,42862
<     "location": "Sweden",
<     "country_id": "se"
---
>     "location": "Finland",
>     "country_id": "fi"
42871,42872c42871,42872
<     "location": "Sweden",
<     "country_id": "se"
---
>     "location": "Finland",
>     "country_id": "fi"
3254954c3254954
< ]
\ No newline at end of file
---
> ]
```

The change is I moved from Sweden to Finland, so changing `Sweden` -> `Finland` and `se` -> `fi` for `lentzi90` (there are two entries, one for my private email and one for the github noreply email).

**Comment by lukaszgryglicki** [comment]
On it, closing this PR - will update manually instead.

**Comment by lentzi90** [comment]
Thank you!

**Comment by lukaszgryglicki** [comment]
Done. Also on `cncf/devstats` side.

**Pull request closed without merging**
