### PR TITLE
please remove my data

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Merged, and cleared data in another commit.

**Comment by codefromthecrypt** [comment]
thanks!

**Comment by codefromthecrypt** [comment]
I still see my data in the following, can you check your script or
otherwise scrub it?

affiliation_finder/fullcontact_lookup_data.csv
cncf-config/email-map
all_affs.csv

**Comment by lukaszgryglicki** [comment]
What is the exact token (not SHA), because I don't know what to remove, maybe I've missed something?
If you don't want to put it there, pelase send email to: lukaszgryglicki@o2.pl

**Comment by codefromthecrypt** [comment]
If you run the following you'll see I'm not scrubbed yet

ag '(adrian.f.cole|Adrian Cole|adrianfcole)'

**Comment by lukaszgryglicki** [comment]
Ok I got it, some SHAs had no hit, so I removed them.
Maybe there was a typo with data to remove when calling add_forbidden_data.rb
Anyway, I'll update forbidden SHAs now and remove again.

**Comment by lukaszgryglicki** [comment]
Should be OK now.

**Comment by codefromthecrypt** [comment]
yep think you got it now. thanks for the fast turnaround

**Pull request merged**
