### PR TITLE
Update wrowe status to Independent

### PR DESCRIPTION
**Pull request by wrowe**
Signed-off-by: William A Rowe Jr <wrowe@rowe-clan.net>

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Why removed 2 emails?
- no longer current?
or
- were never yours?

I think they're no longer current because both have your `username` and then domain like `!users.noreply.github.com` -> which is correct for your GitHub username.
We need to keep historical emails to track historical data from GitHub archives, so I'll keep them and only update affiliations, is this OK?

**Comment by wrowe** [comment]
It is fine to restore those references as long as they don't imply current attribution or a roitable email recipient, thanks.

**Comment by lukaszgryglicki** [comment]
OK, so this is exactly what I did, thx.

**Pull request merged**
