### PR TITLE
fix affiliation for astencel-sumo

### PR DESCRIPTION
**Pull request by andrzej-stencel**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, are you removing your previous affiliation because they were incorrect, or you just keep the current one? Asking because we want to track current & past affiliations...

**Comment by andrzej-stencel** [comment]
The GitHub user @astencel-sumo is only affiliated with Sumo Logic company. This GitHub account was created after I joined Sumo Logic in September 2020 and didn't exist before. The previous affiliations are (partially) correct in the sense that I - Andrzej Stencel, a physical person - did work for some of these companies, but I didn't use the @astencel-sumo GitHub handle back then. Does this make sense?

**Comment by lukaszgryglicki** [comment]
OK, it would be great to have a correct list then, even if the GH account wasn't used - but if you decide to do just one company it is also OK, just let me know your final decision.

**Comment by lukaszgryglicki** [comment]
@astencel-sumo ?

**Comment by andrzej-stencel** [comment]
For this GitHub handle @astencel-sumo I think it makes sense to only use this one company Sumo Logic. Thanks!

**Comment by lukaszgryglicki** [comment]
OK

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
