### PR TITLE
Update email address for @tigrannajaryan

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Please update the affiliation file to include my new email address.
Thank you.

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Missing comma in email, but I'll merge anyway and then regenerate affiliations file.

**Comment by lukaszgryglicki** [comment]
Updated in 013b243802ae86eeb5b64dfabe9e888276432786

**Comment by tigrannajaryan** [comment]
@lukaszgryglicki sorry about the missing comma and thank you for correcting and merging.

I am still not seeing the right affiliation, for some reason in `src/github_users.json` my affiliation is shown  as:
```
"affiliation": "VMware < 2015-11-01, ezhome < 2018-01-01, ezhome < 2018-01-01",
``` 
Somehow ezhome is listed twice and my current company Omnition is not listed at all. Is there anything else that I need to do fix this?

**Comment by lukaszgryglicki** [comment]
Must be my bad, I'll double check tomorrow.

**Comment by tigrannajaryan** [comment]
Thank you.

**Comment by lukaszgryglicki** [comment]
Fixed in 011adc82d64dc069b0a2a835b1d828ae99bb1bad

**Comment by tigrannajaryan** [comment]
@lukaszgryglicki thank you for fixing. I can now see the correct affiliations in this repo and they seem to be also correctly imported to devstats project, however devstats dashboards still show incorrect numbers.

I opened a separate issue here to track it: https://github.com/cncf/devstats/issues/201

Can you please help? I am not sure if it is something that I am doing wrong, I will be happy to fix if you tell me what I need to do.

Thank you for looking.

**Pull request merged**
