### PR TITLE
add affiliation for TimothyMothra

### PR DESCRIPTION
**Pull request by TimothyMothra**
Adding myself to developer affiliations. 
cc @reyang

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
I alraedy have you as: `Bridgeline < 2014-11-01, Northrop Grumman < 2016-08-01, QGenda < 2016-11-01, Microsoft Corporation, source: manual` - is this incorrect - shoudl I overwite it with just Microsoft?

**Comment by TimothyMothra** [comment]
Hi @lukaszgryglicki, that list is correct. But I never did any open-source work for those other companies so I'm not sure how you have that list.
I think it can be overwritten with just Microsoft.

**Comment by lukaszgryglicki** [comment]
OK will ensure this is the case now manually.

**Pull request merged**
