### PR TITLE
update my company affliation

### PR DESCRIPTION
**Pull request by linsun**

### CODE REVIEW

**Comment by linsun** [comment]
cc @ jenshu

**Comment by linsun** [comment]
@lukaszgryglicki thanks for merging this.  Could you please advise what else I may need to do to change company affliction?  my goal is to have CNCF teststats to pick up contribution under the new employer.

**Comment by lukaszgryglicki** [comment]
Now you need to wait. DevStats fetches new affiliations for projects weekly, each project has its own (separate and different) crontab.

**Comment by linsun** [comment]
Thanks @lukaszgryglicki for confirming that! :)

**Pull request merged**
