### PR TITLE
update affiliation for windydayc

### PR DESCRIPTION
**Pull request by windydayc**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Is this a wrong emails removal (like those emails were never yours)? Or maybe they were yours in the past and you no longer use them? In the latter case, we need to keep track of historical emails, in the first case, it's OK to remove them.

**Comment by windydayc** [comment]
> Is this a wrong emails removal (like those emails were never yours)? Or maybe they were yours in the past and you no longer use them? In the latter case, we need to keep track of historical emails, in the first case, it's OK to remove them.

@lukaszgryglicki 
I added my info to this project 25 days ago, but after I submitted pr in the cncf openyurt project, the openyurt Company Commits Table in the Grafana pane  does not show my affiliated message. 
I want to know what's wrong, so try changing this?

**Comment by lukaszgryglicki** [comment]
If those emails are wrong, then removing them is OK. I will merge this. Affiliations data is imported once per month, each project is imported on a different day/hour through the entire month. If you miss your data somewhere - please paste a link here, give a GitHub ID/login of the user that is missing/has wrong data - I'll check manually ad see what the data is.

**Comment by windydayc** [comment]
@lukaszgryglicki 
Thanks. The emails are correct.

Here is the openyurt Company Commits Table: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1
Here is my today's PR (it has been merged) : https://github.com/openyurtio/openyurt/pull/608

The Company Commits Table does not show my affiliated message.

Sorry to trouble you, I don't know where the problem is.

**Comment by windydayc** [comment]
@lukaszgryglicki 
My github login account is 2352661414@qq.com , and github username is windydayc

**Comment by windydayc** [comment]
> @lukaszgryglicki Thanks. The emails are correct.
> 
> Here is the openyurt Company Commits Table: https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1 Here is my today's PR (it has been merged) : [openyurtio/openyurt#608](https://github.com/openyurtio/openyurt/pull/608)
> 
> The Company Commits Table does not show my affiliated message.
> 
> Sorry to trouble you, I don't know where the problem is.

That is my first pr in openyurt, so there is no previous data as a reference to prove whether gitdm is effective

**Comment by lukaszgryglicki** [comment]
OK will take a look at this on Monday. But note that if you only have one PR it is possible it will be skipped - only top N companies are shown - not all the long tail for every single company that has a single PR.
Will investigate this in detail and update you on Monday.

**Comment by windydayc** [comment]
> OK will take a look at this on Monday. But note that if you only have one PR it is possible it will be skipped - only top N companies are shown - not all the long tail for every single company that has a single PR. Will investigate this in detail and update you on Monday.

Yes, this is my first PR in openyurt since the gitdm project was added, but my company(SEL-Zhejiang University) is not . Many of my friends from the company(SEL-Zhejiang University)  have already made lots of contributions in the openyurt repo, and their affiliations data are correctly show [there](https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1).

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
```
openyurt=# select * from gha_actors where login = 'windydayc';
    id    |   login   | name | country_id | sex | sex_prob | tz | tz_offset | country_name | age 
----------+-----------+------+------------+-----+----------+----+-----------+--------------+-----
 43909149 | windydayc |      |            |     |          |    |           |              |    
(1 row)

openyurt=# select * from gha_actors_affiliations where actor_id = 43909149;
 actor_id | company_name | original_company_name | dt_from | dt_to | source 
----------+--------------+-----------------------+---------+-------+--------
(0 rows)

openyurt=# 
```

Your enrollments weren't imported yet, I'll do that manually now and then check the dashboard.

**Comment by lukaszgryglicki** [comment]
Imported manually, and now your contribution [shows up](https://openyurt.devstats.cncf.io/d/56/company-commits-table?orgId=1&var-repogroups=All&var-companies=SEL-Zhejiang%20University).

**Comment by windydayc** [comment]
@lukaszgryglicki Thank you very much! I really appreciate your help.

One more question by the way, how are the names in parentheses added ? Like the picture:

image

**Comment by lukaszgryglicki** [comment]
This is a list of known names that were specified in GitHub, see github_users.json file - it lists all entries for each GitHub id - there is a JSON property `name` there.

**Pull request merged**
