### PR TITLE
update asmitbm affiliation

### PR DESCRIPTION
**Pull request by asmitbm**
I have updated my affiliation in developers_affiliations1.txt. I had a few doubts/questions:

1. Recently I changed my GitHub username from **Asmit2952** to **asmitbm**. Will this change affect my previous contributions to CNCF Projects?
2. I am from India but on checking this [page](https://all.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=ORAS&var-country_name=India), my username is not available under India.
3. I am a student and had participated in few student programs such as LFX Mentorship, Google Summer of Code, Google Season of Docs. Do I need to mention those affiliations?

Thanks!

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
We parse historical data so your contributions will be visible under two github user names - old and new, say we are getting data from 2020-02-03 day from GitHub archive - that data was gathered and archived in github archives at that day, so it will have your old username.
You can list organizations for you old username with date ranges and emails list and then do the same for the new username.
Up to you.

Those:
```
LFX Mentorship, Google Summer of Code, Google Season of Docs
```
Aree not organizations/affiliations - I would rather call them `projects`. What matters is for who you were working for? Yourself (Independent) or for some company? This is what are affiliations for.

**Comment by asmitbm** [comment]
> We parse historical data so your contributions will be visible under two github user names - old and new, say we are getting data from 2020-02-03 day from GitHub archive - that data was gathered and archived in github archives at that day, so it will have your old username. You can list organizations for you old username with date ranges and emails list and then do the same for the new username. Up to you.
> 
> Those:
> 
> ```
> LFX Mentorship, Google Summer of Code, Google Season of Docs
> ```
> 
> Aree not organizations/affiliations - I would rather call them `projects`. What matters is for who you were working for? Yourself (Independent) or for some company? This is what are affiliations for.

Thanks for the prompt answer @lukaszgryglicki.  So, in this txt file, I removed my old username, should I add it back? 

Also, how do I fix the incorrect country filter?

**Comment by lukaszgryglicki** [comment]
But I don't think you should remove the old username - old data will still have it - so I think you should list `both` with the same affiliation (Independent).
For country let me know which country it is and I will update JSON myself (it is calculated from GitHub location).

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by asmitbm** [comment]
> But I don't think you should remove the old username - old data will still have it - so I think you should list `both` with the same affiliation (Independent). For country let me know which country it is and I will update JSON myself (it is calculated from GitHub location).

Hey @lukaszgryglicki, made the changes. Can you please verify?

As for the country, I am from **India**.

**Comment by asmitbm** [comment]
Thank you for all the help :)

**Comment by lukaszgryglicki** [comment]
I've merged and will update country in post-merge.

**Pull request merged**
