### PR TITLE
chore: Tom Kerkhove now works for Microsoft

### PR DESCRIPTION
**Pull request by tomkerkhove**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Is this a new affiliation `Microsoft` just starting today or you just want to update `Codit` to `Microsoft` for all time?
If this is a job change from `Codit` to `Microsoft` - can you provide a date when it changed? If you do so - I'll update your affiliation to something like `Codit < YYYY-MM-DD, Microsoft`.
Thanks!

**Comment by tomkerkhove** [comment]
That would be great, thank you! I started working for Microsoft on Nov 1st, 2021.

**Comment by lukaszgryglicki** [comment]
And previously you worked for `Codit`, right?
I'll update tomorrow then, thanks!

**Comment by tomkerkhove** [comment]
Jup

**Pull request merged**
