### PR TITLE
Update affiliation and country id for jiachengxu

### PR DESCRIPTION
**Pull request by jiachengxu**

### CODE REVIEW

**Comment by jiachengxu** [comment]
Hi @lukaszgryglicki, it seems that the change of LFS file is not shown in the PR, and what I have changed is that I removed my location and changed my country_id from `ch` to `cn`.

Also, since I already changed my GitHub username from `JiachengXu` to `jiachengxu` a few years ago, is there a way that I can update in this repo so that the correct name will be displayed in the dashboards as well? I am asking because I am seeing `JiachengXu` in this repo all over the place and I want to update it.

Thanks in advance.

**Comment by lukaszgryglicki** [comment]
I will update your country and location manually, we treat GitHub usernames as case-insensitive and display the first value as appeared in GitHub archives, so I cannot change your username to lowercase everywhere in any easy step -  I can `try` to update github_users.json manually but not sure if that won't be overwritten in the future and it woudl take a long time to populate everywhere.

**Review by lukaszgryglicki — APPROVED** [review]

**Comment by lukaszgryglicki** [comment]
Also I'll close this PR and merge manually becauzse I don't know your LFS changes and can't just merge blindly, so I will do manual updates in exactly the same way as your PR does.

**Comment by lukaszgryglicki** [comment]
this is done, will be committed with my next batch.

**Pull request closed without merging**
