### PR TITLE
Update affiliation for yeya24

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <benye@amazon.com>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, are you removing one email address because it is no longer current or it was just wrong?
- In 1st case we want to keep it, because we're tracking historical data.
- In 2nd case it's Ok to remove it.
Thanks!

**Comment by yeya24** [comment]
@lukaszgryglicki Thanks for the reply. Yeah it is case 1, but it is also kind of confusing to me because other email addresses I was using while contributing are not tracked here so I thought it only wants to track the latest work email.

Btw I found my name appear in multiple files. Should I update them all? Thanks!
image

**Comment by lukaszgryglicki** [comment]
No you just update this one file, as you perfectly did!
All I need is:
```
github-user-name: email1, email2, (...), emailN:
  Company1 until YYYY-MM-DD
  Company2 from YYYY-MM-DD until YYYY-MM-DD
(...)
  CompanyN from YYYY-MM-DD
```

Just see other entries in the same file you modified, thanks!
Other places (those where it is currently needed) will be automatically updated in post-merge.

**Comment by yeya24** [comment]
@lukaszgryglicki Updated!

**Comment by lukaszgryglicki** [comment]
Thx, will merge tomorrow.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
