### PR TITLE
Update affiliation for several Googlers who moved to VMWare

### PR DESCRIPTION
**Pull request by evankanderson**
@mattmoor
@n3wscott
@vaikas

### CODE REVIEW

**Comment by mattmoor** [comment]
11/4 was technically day 1 VMware.  Last day at google was 11/1

**Comment by evankanderson** [comment]
Updated.

**Comment by evankanderson** [comment]
Sorry, I missed that I needed to merge. Let me know if you need me to squash history further.

**Comment by lukaszgryglicki** [comment]
Please remove `developers_affiliations4.txt` file (this commits attempts to add this file). I will merge this as soon as possible - when I have some time.

**Comment by evankanderson** [comment]
Sorry about that; I got very confused in the merge and ended up cancelling and continuing at an inopportune time.

Fixed.

**Comment by lukaszgryglicki** [comment]
Will merge tomorrow, thanks.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
