### PR TITLE
Update affiliation for `maiqueb`

### PR DESCRIPTION
**Pull request by maiqueb**
Correct user affiliation.

### CODE REVIEW

**Comment by maiqueb** [comment]
Fixes https://github.com/cncf/devstats/issues/275

**Comment by lukaszgryglicki** [comment]
We usually leave the preevious companies list.
For example
```
somebody: someemail@domain.com:
  Company1 < 2020-11-01
  Company2
```
You can of course skip it, but then everything you did on the previous company will be assigned to the new one.

**Comment by maiqueb** [comment]
> We usually leave the preevious companies list.
> For example
> 
> ```
> somebody: someemail@domain.com:
>   Company1 < 2020-11-01
>   Company2
> ```
> 
> You can of course skip it, but then everything you did on the previous company will be assigned to the new one.

I understand and considered it, but I never worked on anything cncf related while working for those companies. Actually, this user was created when I joined Red Hat. 

That is why I've decided to update it like that.

**Comment by lukaszgryglicki** [comment]
OK, merging then.

**Pull request merged**
