### PR TITLE
Rename 'Raintank Inc. – Grafana Labs' to 'Grafana Labs'

### PR DESCRIPTION
**Pull request by fstab**
In case you need verification for this: I work at Grafana and I'm a member of the Grafana Labs organization on Github, https://github.com/fstab/.

Signed-off-by: Fabian Stäber <fabian@fstab.de>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
@fstab  Is this just for all users who were `Raintank Inc. – Grafana Labs` to replace with `Grafana Labs` ?
If so I will update mapping filke and regenerate all data - will be a lot less work and will make sure all occurences are replaced?

**Comment by fstab** [comment]
Yes, my intention is to replace `Raintank Inc. – Grafana Labs` with `Grafana Labs` everywhere. Thanks a lot!

**Comment by lukaszgryglicki** [comment]
On it...

**Comment by lukaszgryglicki** [comment]
Done, closing this PR because I did this using automatic tools and added mapping for this.

**Pull request closed without merging**
