### PR TITLE
Fix GitHub account

### PR DESCRIPTION
**Pull request by ziyi-xie**

### CODE REVIEW

**Comment by ziyi-xie** [comment]
Sorry that I wrote my name of the Github account wrong.(*ﾉω・*)

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by ziyi-xie** [comment]
@lukaszgryglicki Thank you so much for your approval! And I just noticed that the 761th line in [developers_affiliations6.txt](https://github.com/cncf/gitdm/blob/88d97f4af9a4b230363a3607a057c0ab09eeef4d/developers_affiliations6.txt#L761) file and the 15052th line in [company_developers5.txt](https://github.com/cncf/gitdm/blob/88d97f4af9a4b230363a3607a057c0ab09eeef4d/company_developers5.txt#L15052) file are still having my previous name on it, and I guess it's added [automatically.](https://github.com/cncf/gitdm/commit/88d97f4af9a4b230363a3607a057c0ab09eeef4d#diff-4e8c9ddf25a5a4ab50ea2a9d154b447f48bebe8bc1640bb983c9c34d89c02f29) Could I ask that is it removable? And how can I do to remove it? Looking forward to hearing from you and many thanks. :)

**Comment by lukaszgryglicki** [comment]
First of all, if you had a previous GitHub account then it needs to be tracked, because we track historical data from archives, so past files will have an old name. If there is a GitHub account that was never yours (but with your email) let me know which exactly and I'll remove it manually.

**Comment by ziyi-xie** [comment]
Thank you so much for you reply! The [xieziyi] account is actually the one I registered with the wrong account name by mistake. It is not me and also not belong to the NEC Corporation. Could you delete it please. Many thanks! :)

**Comment by lukaszgryglicki** [comment]
Back on this, will update and let you know.

**Comment by lukaszgryglicki** [comment]
Done.

**Comment by ziyi-xie** [comment]
Thanks a lot! Really appreciate your help~

**Pull request merged**
