### PR TITLE
Update NATS team affiliations

### PR DESCRIPTION
**Pull request by derekcollison**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
There is no "from" keyword in this file.
There is only until to mark some job as a finished, and one final job with no "until" that means current.
I won't merge this, but I'll just update file manually using this PRs diff.
I'll let you know when complete.

**Comment by lukaszgryglicki** [comment]
I've reproduced your changes here: e178c115d4c6e62408fdc39e9c68aeb0054c55ad. Closing this.
I'll regenerate all remining files now.

**Comment by lukaszgryglicki** [comment]
BTW: we cannot group all emails by user name like "Collin Sullivan" because final files are generated via commit analysis, so GitHub reported user name is used for groupping.
There are 3 other names actually:
- Real user name (we don't actually have it)
- GitHub reported user name (which can be different on different machines etc), all emails would be groupped under single name if user is always using the same `git --name` property.
- GitHub login - this is uninque can can map to multiple names and emails. There can be for example 3 different names and 6 different emails.

It is perfectly OK to create PRs like this, but final state will be groupped by GitHub "name" and then emails.

**Comment by lukaszgryglicki** [comment]
I've just pushed the final affiliations files:
3f901150ec4eee9bb72b0eb40dc850e554c2a55b

**Comment by lukaszgryglicki** [comment]
New affiliations imported into https://nats.devstats.cncf.io

**Comment by derekcollison** [comment]
Thanks.

**Pull request closed without merging**
