### PR TITLE
add Shelby, Paul, and Irving.

### PR DESCRIPTION
**Pull request by lizthegrey**
cc @shelbyspees @paulosman

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Ideally if there is just some company `from` there should also be another with `until`. It can be `Independent` for example.

**Comment by lizthegrey** [comment]
Understood. I will update accordingly, didn't want to steal credit for their previous contributions.

**Comment by lukaszgryglicki** [comment]
Thanks, we just need a list of companies that cover a full range from about 2014 to now. In many cases we don't have and use Unknown then or Independent.

**Comment by lizthegrey** [comment]
PTAL @lukaszgryglicki

**Pull request merged**
