### PR TITLE
add affiliation for nehalohia

### PR DESCRIPTION
**Pull request by nehaLohia27**
Signed-off-by: Neha Lohia <nehapithadiya444@gmail.com>

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Conflicts, I'll close this and resolve manually.

**Comment by nehaLohia27** [comment]
thanks @lukaszgryglicki .

**Comment by nehaLohia27** [comment]
@lukaszgryglicki Are these changes merged into master ?

**Comment by lukaszgryglicki** [comment]
Yes, see:
- https://github.com/cncf/gitdm/blob/master/company_developers4.txt#L6365
- https://github.com/cncf/gitdm/blob/master/company_developers7.txt#L8063
- https://github.com/cncf/gitdm/blob/master/developers_affiliations4.txt#L6068-L6070

**Pull request closed without merging**
