### PR TITLE
Add ipochi's affliation

### PR DESCRIPTION
**Pull request by ipochi**
Signed-off-by: Imran Pochi <imranpochi@microsoft.com>

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
I've merged with existing data manually in post-merge.
We already had some contributions before Kinvolk so I just kept them and then udpated Kinvold & Microsoft to match your PR.

**Comment by ipochi** [comment]
@lukaszgryglicki Sorry I didn't get you. Could you please help me understand.

**Comment by ipochi** [comment]
@lukaszgryglicki 

Despite the PR getting merged, I don't see my name listed ?

https://github.com/cncf/gitdm/search?q=ipochi


My details are removed in this commit/
https://github.com/cncf/gitdm/commit/b666b0e4af2ebfe94673b20e447c7bb692fd8898

**Comment by lukaszgryglicki** [comment]
Those TXT files are auto merged, I can see your details in main file [github_users.json](https://github.com/cncf/gitdm/blob/master/src/github_users.json):
```
  {
    "login": "ipochi",
    "email": "imran!kinvolk.io",
    "affiliation": "Accenture Global Solutions Limited < 2016-09-01, ITC Infotech < 2017-10-01, Infracloud Technologies INC < 2019-01-01, Independent < 2019-09-01, Kinvolk GmbH < 2021-05-27, Microsoft Corporation",
    "source": "user_manual",
    "name": "Imran Pochi",
    "commits": 148,
    "location": "Bangalore",
    "country_id": "in"
  },
  {
    "login": "ipochi",
    "email": "imranpochi!microsoft.com",
    "affiliation": "Accenture Global Solutions Limited < 2016-09-01, ITC Infotech < 2017-10-01, Infracloud Technologies INC < 2019-01-01, Independent < 2019-09-01, Kinvolk GmbH < 2021-05-27, Microsoft Corporation",
    "source": "user_manual",
    "name": "Imran Pochi",
    "commits": 148,
    "location": "Bangalore",
    "country_id": "in"
  },
  {
    "login": "ipochi",
    "email": "ipochi!users.noreply.github.com",
    "affiliation": "Accenture Global Solutions Limited < 2016-09-01, ITC Infotech < 2017-10-01, Infracloud Technologies INC < 2019-01-01, Independent < 2019-09-01, Kinvolk GmbH < 2021-05-27, Microsoft Corporation",
    "source": "user_manual",
    "name": "Imran Pochi",
    "commits": 148,
    "location": "Bangalore",
    "country_id": "in"
  },
  {
    "login": "ipochi",
    "email": "pochiimran!yahoo.co.in",
    "affiliation": "Accenture Global Solutions Limited < 2016-09-01, ITC Infotech < 2017-10-01, Infracloud Technologies INC < 2019-01-01, Independent < 2019-09-01, Kinvolk GmbH < 2021-05-27, Microsoft Corporation",
    "source": "user_manual",
    "name": "Imran Pochi",
    "commits": 148,
    "location": "Bangalore",
    "country_id": "in"
  },
```
Also in second file [cncf-config/email-map](https://github.com/cncf/gitdm/blob/master/src/cncf-config/email-map)
```
ipochi!users.noreply.github.com Accenture Global Solutions Limited < 2016-09-01
ipochi!users.noreply.github.com ITC Infotech < 2017-10-01
ipochi!users.noreply.github.com Independent < 2019-09-01
ipochi!users.noreply.github.com Infracloud Technologies INC < 2019-01-01
ipochi!users.noreply.github.com Kinvolk GmbH < 2021-05-27
ipochi!users.noreply.github.com Microsoft Corporation
(...)
imran!kinvolk.io Accenture Global Solutions Limited < 2016-09-01
imran!kinvolk.io ITC Infotech < 2017-10-01
imran!kinvolk.io Independent < 2019-09-01
imran!kinvolk.io Infracloud Technologies INC < 2019-01-01
imran!kinvolk.io Kinvolk GmbH < 2021-05-27
imran!kinvolk.io Microsoft Corporation
(...)
imranpochi!microsoft.com Accenture Global Solutions Limited < 2016-09-01
imranpochi!microsoft.com ITC Infotech < 2017-10-01
imranpochi!microsoft.com Independent < 2019-09-01
imranpochi!microsoft.com Infracloud Technologies INC < 2019-01-01
imranpochi!microsoft.com Kinvolk GmbH < 2021-05-27
imranpochi!microsoft.com Microsoft Corporation
```

And also in TXT files:
- [developers_affiliations3.txt](https://github.com/cncf/gitdm/blob/master/developers_affiliations3.txt#L21230-L21236)
And company affiliations files:
```
root@darkstar:~/go/src/github.com/cncf/gitdm/src# grep ipochi ../*.txt
../company_developers1.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in until 2016-09-01
../company_developers3.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in from 2016-09-01 until 2017-10-01
../company_developers4.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in from 2019-01-01 until 2019-09-01
../company_developers5.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in from 2017-10-01 until 2019-01-01
../company_developers5.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in from 2019-09-01 until 2021-05-27
../company_developers5.txt:	ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in from 2021-05-27
../developers_affiliations3.txt:ipochi: imran!kinvolk.io, imranpochi!microsoft.com, ipochi!users.noreply.github.com, pochiimran!yahoo.co.in
root@darkstar:~/go/src/github.com/cncf/gitdm/src# vim ../developers_affiliations3.txt
```

So, I think all is OK. After almost all merges I'm regenerating text files & cncf-confil/emial-map and GitHub_users.json.

**Pull request merged**
