### PR TITLE
Update tallclair affiliation & email

### PR DESCRIPTION
**Pull request by tallclair**

### CODE REVIEW

**Comment by tallclair** [comment]
No idea how lenymo@gmail.com got associated with me...

**Comment by tallclair** [comment]
It's a little concerning actually. Any idea how to tell where that came from?

**Comment by caniszczyk** [comment]
@tallclair good question, on the initial import of a project we try to match based on what information we find in commit messages and other source of info, in this case, not sure

@lukaszgryglicki any comments here?

**Comment by lukaszgryglicki** [comment]
Really hard to tell now, we have some initial imports from automatic tools (many different) and some data was incorrect due to this. Merging this and fixing data.

**Pull request merged**
