### PR TITLE
Fix jewertow's affiliation

### PR DESCRIPTION
**Pull request by jewertow**
Signed-off-by: Jacek Ewertowski <jacek.ewertowski1@gmail.com>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
It's OK and I will merge it but I'm just asking - are there all your affiliations for all-time or you just prefer to list only Red Hat?

**Comment by jewertow** [comment]
I prefer to list only Red Hat, because it's the only company where I have contributed to CNCF projects.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Will regenerate JSON (gitdm & devstats) in post-merge (ETA: a few mins).

**Pull request merged**
