### PR TITLE
changed arkajyotiMukherjee from Mayadata to ChaosNative

### PR DESCRIPTION
**Pull request by arkajyotiMukherjee**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Did your emails just changed (you removed one), or it was an incorrect email?
If this is just a no longer used email (historical one) then we want to keep it because we track historical data too.

**Comment by arkajyotiMukherjee** [comment]
@lukaszgryglicki I'm sorry I was not aware that historical data was tracked... I'll add it back.
Thanks for the info.

**Comment by lukaszgryglicki** [comment]
Don't need to, I just haven't removed that until you confirm that the email is not yours, so now the state is OK and files are being regenerated just now.

**Comment by arkajyotiMukherjee** [comment]
Thanks @lukaszgryglicki

**Pull request merged**
