### PR TITLE
Fix developer affiliation for github.com/kovrus.

### PR DESCRIPTION
**Pull request by kovrus**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by kovrus** [comment]
Hi @lukaszgryglicki , do you know when this change can be reflected on https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1?
Thanks!

**Comment by lukaszgryglicki** [comment]
I can run manual import now. Let me do this - normally it takes up to about 4 weeks.

**Comment by lukaszgryglicki** [comment]
@kovrus done, please check [this dashboard](https://opentelemetry.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=Last%20decade&var-metric=contributions&var-repogroup_name=All&var-country_name=Germany&var-companies=Grafana%20Labs).

**Comment by kovrus** [comment]
@lukaszgryglicki thanks! It looks fine now!

**Pull request merged**
