### PR TITLE
Update rata's affiliation

### PR DESCRIPTION
**Pull request by rata**
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>

### CODE REVIEW

**Comment by rata** [comment]
Oops, updated to not modify the company_developers* files now :)

**Comment by lukaszgryglicki** [comment]
Hi you changed two addresses `rata!users.noreply.github.com, rodrigo!sdfg.com.ar` to Independent and added two `rodrigoca!micorosoft.com, rodrigo!kinvolk.io` for Microsoft - we need all addresses and time ranges for independent & Microsoft, please update.

**Comment by rata** [comment]
@lukaszgryglicki both happen in parallel. I still contribute in my spare time, that is not sponsored by Microsoft. Isn't it possible to keep both as separate?

**Comment by lukaszgryglicki** [comment]
Currently we affiliate to one company at a time per github handle - because we only have emails from commits (git) and all other activity from GitHub, so if the same github handle (using different emails) do any contribution (probably other than commit) we just know that given GitHub ID did comment/review/create an issue or PR - we don't know which email from that account did this.
So, unfortunatelly, there can be one company affiliation at given point in time for one github handle.

EDIT: we can think about separate affiliations in different projects actually, like having optional "project" field in affiliation file and then if processing data for given CNCF project give priority to that project specific affiliations (if any) with fallback to those without "project" (say, global).

But this would be a new feature, nothing we have right now.

**Comment by rata** [comment]
@lukaszgryglicki ohh, thanks a lot for the explanation. Updated to attribute it to only one company in any period of time, then :)

**Comment by lukaszgryglicki** [comment]
Thanks, will approve & merge tomorrow.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
