### PR TITLE
Update affiliation for sonasingh46

### PR DESCRIPTION
**Pull request by sonasingh46**
cc @lukaszgryglicki

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Just the question: are those emails yours, but no longer used? (in such case we want to keep them, for affiliating historical contents) or maybe they are just wrong? (in this case, we should remove them, exactly as in this PR).

**Comment by sonasingh46** [comment]
Those emails were mine but I no longer have access to those.

**Comment by lukaszgryglicki** [comment]
OK, so I did change in post-merge and kept them. Our tools track contributions over time, so we need historical emails too.

**Pull request merged**
