### PR TITLE
update craicoverflow affiliations

### PR DESCRIPTION
**Pull request by craicoverflow**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Is this meail incorrect, or just historical?
If this is historical, we should keep it, because we also track past data.

**Comment by lukaszgryglicki** [comment]
Is `redhat` address incorrect, or just historical. If historical we want to keep it, so we can also track historical contributions.

**Comment by lukaszgryglicki** [comment]
Hi, are you removing the email address because it was never yours (a bug) or just because it is no longer current? If the latter then we want to keep it, because we want to track past contributions...

**Comment by lukaszgryglicki** [comment]
I would assume that this is a historical email if no feedback is received in a few days, thanks.

**Comment by craicoverflow** [comment]
I'm very sorry, I have not been receiving any emails for your replies and happened to see it today (I am no longer very active on GitHub).

`penda@redhat.com` never existed, it was a bug. However I have now amended it to include `ephelan@redhat.com` (historical).

**Comment by lukaszgryglicki** [comment]
No issues, thanks for the info!

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
