### PR TITLE
Added new Cortex contributors from Grafana Labs

### PR DESCRIPTION
**Pull request by pstibrany**
Added new contributors from Grafana Labs: @pracucci, @joe-elliott, @owen-d and @pstibrany.

### CODE REVIEW

**Review by pracucci — APPROVED** [review]
Thanks!

**Review by owen-d — APPROVED** [review]
👍 from me. Thanks, @pstibrany

**Comment by joe-elliott** [comment]
Everyone spells my name wrong @pstibrany.  No worries :)

Thanks!

**Comment by pstibrany** [comment]
Added @slim-bean, and @rfratto.

**Comment by pstibrany** [comment]
Thanks!

**Pull request merged**
