### PR TITLE
Add yagonobre affiliation

### PR DESCRIPTION
**Pull request by yagonobre**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Actually, I had a more detailed affiliations list:
```
nobre.yago!gmail.com Circulo Do Coracao < 2014-10-01
nobre.yago!gmail.com In Laco Media < 2017-06-01
nobre.yago!gmail.com Luizalabs < 2018-04-01
nobre.yago!gmail.com Nubank
nobre.yago!gmail.com Nucleo de Telessaude do UFPE < 2016-07-01
```
Is it correct? If so, I'll prefer to use a more detailed list that just a final affiliation `Nubank`.
@yagonobre ?

**Comment by yagonobre** [comment]
Thanks @lukaszgryglicki, yes it's make sense to have a more detailed list!
```
nobre.yago!gmail.com Circulo Do Coração < 2014-10-01
nobre.yago!gmail.com Nucleo de Telessaude da UFPE < 2016-07-01
nobre.yago!gmail.com In Loco Media < 2017-06-01
nobre.yago!gmail.com Luizalabs < 2018-04-01
nobre.yago!gmail.com Nubank

```

**Comment by lukaszgryglicki** [comment]
OK, I'll update this manually on Friday.

**Comment by lukaszgryglicki** [comment]
Updated in d2a8c6db30d52da88694101d69d1a250a4591088

**Pull request merged**
