### PR TITLE
Adding Dynatrace LLC to the domain map

### PR DESCRIPTION
**Pull request by aepfli**
As I understood, this should improve the automatic mapping of our
employees to the Dynatrace organization, as they're using
their company email. If not, please let me know if there is a way
to achieve this.

Thank you

Signed-off-by: Simon Schrottner <simon.schrottner@dynatrace.com>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
We don't use domain mapping as this is usually worse than manual research. Ideally, create a PR that just adds users with correct affiliations - just like most PRs here.
I will merge this, but this mapping is not a part of the workflow for a long time.
I can also manually add users for you - just send me a list of emails and GitHub logins.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by aepfli** [comment]
Thank you for the fast response.

It looks like we will need to setup some tooling to figure this out. Eg. by scanning all our users, it is hard to have an overview, of who actually contributed to which project - and who is actually somehow affiliated with us or not. we will discuss this internally, and maybe there will be some kind of PR from our side.

Thank you!

**Comment by lukaszgryglicki** [comment]
Thanks!

**Pull request merged**
