### PR TITLE
Update josh-ferrell affiliation

### PR DESCRIPTION
**Pull request by josh-ferrell**
Updating company affiliation

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Hi, are you removing the email address because it was never yours (a bug) or just because it is no longer current? If the latter then we want to keep it, because we want to track past contributions...

**Comment by josh-ferrell** [comment]
@lukaszgryglicki sorry about that, added it back in.

**Comment by lukaszgryglicki** [comment]
No problem, will approve and merge probably tomorrow.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
