### PR TITLE
Update silenceshell company affiliation

### PR DESCRIPTION
**Pull request by silenceshell**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
just wonder - have you just changed a company affiliation recently? or maybe you never worked for Jd.com?
Asking because if this is just a change then you can provide when it happened like:
```
silenceshell:  hubottle!gmail.com
  Jd.com until YYYY-MM-DD
  Tencent Holdings Limited
```

**Comment by silenceshell** [comment]
oh I see. Will new a PR to fix it, thanks~

**Comment by lukaszgryglicki** [comment]
You can do that, or just let me know the date - I'll do that manually then - I need to run post-merge tools anyway, so it's not a problem...

**Comment by silenceshell** [comment]
I works for Jd.com until 2021-09-06
Thank you a lot 😁

**Comment by lukaszgryglicki** [comment]
OK, I'll update files and regenrate.

**Pull request merged**
