### PR TITLE
Update affiliation for @tedyu

### PR DESCRIPTION
**Pull request by tedyu**

### CODE REVIEW

**Comment by tedyu** [comment]
@lukaszgryglicki
On this page:
https://k8s.devstats.cncf.io/d/66/developer-activity-counts-by-companies?orgId=1&var-period_name=v1.15.0%20-%20now&var-metric=contributions&var-repogroup_name=All&var-country_name=All&var-companies=All

affiliation for me (tedyu) is still empty.
Do I need to modify another file ?

Thanks

BTW same applies to the other 3 people : akutz, yakarap, joonas

**Comment by lukaszgryglicki** [comment]
PR was merged 2 days ago. Affiliations from `cncf/gitdm` are imported to `cncf/devstats` only 1-2 times/month. It will be updated on the next import. I didn't import anything since at least 2 weeks.

**Comment by tedyu** [comment]
@lukaszgryglicki 
Can you trigger the import in the near future ?

Thanks

**Comment by clintkitson** [comment]
Hey @lukaszgryglicki thanks for looking into this. Ted mentioned a few other committers that look to also not be associated correctly even though the affiliations files look to be accurate. What do you suggest for these other names to ensure they show up correctly as well?

**Comment by lukaszgryglicki** [comment]
Check if they're correctly defined in this repo, I'll trigger new import soon - today or tomorrow.

**Comment by lukaszgryglicki** [comment]
Fixed all mentioned affiliation, I wasn't able to fina any reference to `yakarap` user. there is no such GitHub profile, but I'll update all others. I'll be adding tooling to do automatic affiliations import about twice/week, so give me some time and this data will be fixed and then auto-updated. I'll let you know when new affiliations are imported.

**Comment by clintkitson** [comment]
Apologies for the typo, `ykakarap` is the other name.

@lukaszgryglicki I am not sure what to check at this point. Is there a tool you run to validate results? Tough to understand how the info in the json or affiliate files is being interpreted.

Thanks!

**Comment by lukaszgryglicki** [comment]
I'll check that name and I'm finishing tooling to import affiliations automatically once per week.
I'll let you know when I import current data, it will take some time because I'm just creating automatic cron-jobs now.

**Comment by lukaszgryglicki** [comment]
Actually to add/modify any affiliations data just follow [this section](https://github.com/cncf/gitdm#addingupdating-affiliation) - you just create a single PR against one text file. I'll check `ykakarap` tomorrow.

**Comment by clintkitson** [comment]
That has been clear, but for example Ted Yu looked to have been associated correctly in that file but his affiliation wasn't making it through.

**Comment by lukaszgryglicki** [comment]
Right, I have to mention that DevStats imports that data weekly now.

**Comment by lukaszgryglicki** [comment]
Data is now imported, cronjobs importing new data are added (they import new JSON weekly), also documentation is updated specifying that data from this repo is imported on DevStats monthly.

Tech detail: note that there may be small changes to `github_users.json` in this repo, like work-in-progress, not copied to DevStats `cncf/devstats`:`github_users.json`, to avoid importing any wip-status JSONs, I'm only copying `cncf/gitdm`:`github_users.json` to `cncf/devstats`:`github_users.json` when I finish any temporary work or just generate new file with new affiliations, DevStats imports `cncf/devstats`:`github_users.json` file weekly, not JSON from this repo.

**Pull request merged**
