### PR TITLE
Update affiliation of Bryan Boreham

### PR DESCRIPTION
**Pull request by bboreham**
I moved job.

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm - but not sure about the company name that I should use: `Raintank Inc.` or `Grafana Labs` - we don't use company's subdivisions if this is the case here, I'll update to `Gafana Labs` but let me know if you want me to change to `Raintank Inc.`.

**Comment by bboreham** [comment]
I copied it from another employee of the same company.
There are no subdivisions: Raintank is the legal name and Grafana Labs is the brand.

**Comment by lukaszgryglicki** [comment]
So now I've changed to `Grafana Labs` I can change to `Raintank Inc.` or even to your original name `Raintank Inc. - Grafana Labs` - I was thinking that this is something like "sub-project"/"sub-division" under Grafana labs.

**Comment by bboreham** [comment]
I think the best is to use what I submitted, so it aligns with all the other contributors from that company.

**Comment by lukaszgryglicki** [comment]
Actually, this is the case now - auto mapping includes that company and maps to it. So all should be fine now.

**Pull request merged**
