### PR TITLE
Chainguard additions

### PR DESCRIPTION
**Pull request by vaikas**
This updates the affiliations for @kimsterv @dlorenc @n3wscott @mattmoor and @vaikas to Chainguard Inc.

### CODE REVIEW

**Comment by kimsterv** [comment]
lgtm!

**Review by n3wscott — COMMENTED** [review]
/lgtm

**Comment by dlorenc** [comment]
Lgtm!

**Comment by mattmoor** [comment]
lgtm

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm (missing `,` commas, but I will correct in post-process)

**Comment by vaikas** [comment]
Thanks @lukaszgryglicki !

**Pull request merged**
