### PR TITLE
Fix yann-soubeyrand's affiliation

### PR DESCRIPTION
**Pull request by yann-soubeyrand**
Signed-off-by: Yann Soubeyrand <yann.soubeyrand@gmx.fr>

### CODE REVIEW

**Comment by yann-soubeyrand** [comment]
I’ve two questions:
- I see that informations are wrong in `src/cncf-config/email-map` and `src/github_users.json`. Will these files be updated with the modifications done in this PR?
- I see there are overlaps between affiliations end dates and start dates. Can you confirm that the end date is an excluded upper bound?

**Comment by lukaszgryglicki** [comment]
`I see that informations are wrong in src/cncf-config/email-map and src/github_users.json. Will these files be updated with the modifications done in this PR?` - yes.
`I see there are overlaps between affiliations end dates and start dates. Can you confirm that the end date is an excluded upper bound?` - internally I keep list of affiliations with company and start/end dates, if dates overlap (which shouldn't be the case) contribution will be attibuted to both overlapping companies

**Comment by lukaszgryglicki** [comment]
Also date '2022-08-20' means '2022-08-20 00:00:00', so if start and end date is '2022-08-20' - this means contributions untill '2022-08-20 00:00:00' are for 1st company and any afterthan for 2nd company.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by yann-soubeyrand** [comment]
Thanks for your answers @lukaszgryglicki :wink:

**Pull request merged**
