### PR TITLE
Update developers_affiliations2.txt

### PR DESCRIPTION
**Pull request by divya-mohan0209**
Update my affiliation with HSBC & add affiliation with SUSE

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
No need to do it, those files are either manually merged or automatically regenerated after merges. So this will be auto fixed in the next run.
Go ahead and merge if you want.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by divya-mohan0209** [comment]
Thanks @lukaszgryglicki :) I'll be merging it now!

**Comment by divya-mohan0209** [comment]
@lukaszgryglicki I don't seem to have write access to the repo to merge it. Please could you do the honours?

**Comment by lukaszgryglicki** [comment]
Done.

**Pull request merged**
