### PR TITLE
Updated company affiliation

### PR DESCRIPTION
**Pull request by richardcase**
Signed-off-by: Richard Case <richard.case@outlook.com>

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
Why remove the email address? Was it incorrect or is no loner current? In 1st case, it is OK to remove, in 2nd we prefer to keep it because we want to track past contributions too.

**Comment by richardcase** [comment]
It’s no longer current, I will add it back. Thanks @lukaszgryglicki

**Comment by richardcase** [comment]
Added the email address back in.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Pull request merged**
